{% set name = "pygfunction" %}
{% set version = "2.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pygfunction-{{ version }}.tar.gz
  sha256: 8b319b88ae90dcc625f849cfa6275a1e2e5c884225fff8fc65bb2c20a9bac933

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - matplotlib-base >=3.9.2
    - numpy >=1.26.4
    - scipy >=1.13.1
    - secondarycoolantprops >=1.1
    - typing_extensions >=4.11.0

test:
  imports:
    - pygfunction
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/MassimoCimmino/pygfunction
  summary: A g-function calculator for Python
  license: BSD-3-Clause
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - wouterpeere
