{% set name = "pygfunction" %}
{% set version = "2.2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pygfunction-{{ version }}.tar.gz
  sha256: b0e73bf66c7e3921b957459edf859a96c93ad8e0f6f30c07bb251f82d9f8264e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools
    - wheel
    - pip
  run:
    - python >=3.7
    - matplotlib-base >=3.5.1
    - numpy >=1.21.5
    - scipy >=1.7.3
    - secondarycoolantprops >=1.1

test:
  imports:
    - pygfunction
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/MassimoCimmino/pygfunction
  summary: A g-function calculator for Python
  license: BSD-3-Clause
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - wouterpeere
